import { test } from 'node:test';
import assert from 'node:assert/strict';
import { PassThrough } from 'node:stream';
import { createInterface } from 'node:readline';
import { once } from 'node:events';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { WebSocket } from 'ws';
import { createBridge } from '../bridge/server.mjs';
import { createAdapter, serveStdio } from '../bridge/claude.mjs';
import { installClaudeDesktop } from '../scripts/install-claude-desktop.mjs';

test('Claude stdio discovers the skill, reads the chosen live session and returns images without credentials', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'figma-spark-claude-'));
  const configPath = join(directory, 'connection.json');
  const token = 'fixture-private-token', pairingCode = 'fixture-pair-code';
  const bridge = createBridge({ token, pairingCode, port: 0, configPath });
  const address = await bridge.listen();
  const config = { url: `http://127.0.0.1:${address.port}`, token, pairingCode };
  await writeFile(configPath, JSON.stringify(config), { mode: 0o600 });
  const plugin = new WebSocket(config.url.replace('http:', 'ws:') + '/plugin');
  await once(plugin, 'open');
  const hello = once(plugin, 'message');
  plugin.send(JSON.stringify({ type: 'hello', protocol: 1, token: pairingCode, clientId: 'claude-fixture', context: { fileName: 'Neutral fixture' } }));
  const session = JSON.parse((await hello)[0].toString());
  const received = [];
  plugin.on('message', data => {
    const request = JSON.parse(data.toString());
    if (request.type !== 'request') return;
    received.push(request);
    plugin.send(JSON.stringify({ type: 'response', id: request.id, ok: true, result: request.command === 'export' ? { images: [{ nodeId: '1:2', format: 'PNG', base64: 'aW1hZ2U=' }] } : { command: request.command, params: request.params } }));
  });
  const input = new PassThrough(), output = new PassThrough();
  const pending = new Map();
  const responses = createInterface({ input: output });
  responses.on('line', line => {
    const response = JSON.parse(line);
    pending.get(response.id)?.(response);
    pending.delete(response.id);
  });
  const stdio = serveStdio({ input, output, adapter: createAdapter({ config, ensureService: async () => {} }) });
  t.after(async () => { stdio.close(); responses.close(); input.destroy(); output.destroy(); await bridge.close(); await rm(directory, { recursive: true, force: true }); });
  let id = 0;
  const request = (method, params) => new Promise(resolve => {
    const requestId = ++id;
    pending.set(requestId, resolve);
    input.write(JSON.stringify({ jsonrpc: '2.0', id: requestId, method, params }) + '\n');
  });
  const initialized = await request('initialize', { protocolVersion: '2024-11-05', capabilities: {} });
  assert.equal(initialized.result.protocolVersion, '2024-11-05');
  input.write('{"jsonrpc":"2.0","method":"notifications/initialized"}\n');
  const tools = (await request('tools/list')).result.tools;
  assert.equal(tools.length, 3);
  assert.ok(tools.every(tool => tool.annotations.readOnlyHint));
  const connection = (await request('tools/call', { name: 'figma_spark_connect', arguments: { url: session.connectURL } })).result;
  const discovered = JSON.parse(connection.content[0].text);
  assert.equal(discovered.sessionId, session.sessionId);
  assert.ok(discovered.skill.startsWith('---\nname: figma-spark'));
  assert.ok(!connection.content[0].text.includes(token) && !connection.content[0].text.includes(pairingCode));
  const overview = (await request('tools/call', { name: 'figma_spark_read', arguments: { command: 'overview', sessionId: discovered.sessionId, params: { pageId: '0:1' } } })).result;
  assert.equal(JSON.parse(overview.content[0].text).result.command, 'overview');
  assert.deepEqual(received[0].params, { pageId: '0:1' });
  const image = (await request('tools/call', { name: 'figma_spark_image', arguments: { sessionId: discovered.sessionId, nodeIds: ['1:2'] } })).result;
  assert.equal(image.content[1].type, 'image');
  assert.equal(image.content[1].mimeType, 'image/png');
  assert.ok(!image.content[0].text.includes('aW1hZ2U='));
  const forbidden = (await request('tools/call', { name: 'figma_spark_read', arguments: { command: 'patch', sessionId: discovered.sessionId } })).result;
  assert.equal(forbidden.isError, true);
  assert.equal(received.length, 2);
  const invalidURL = (await request('tools/call', { name: 'figma_spark_connect', arguments: { url: 'https://example.com/connect' } })).result;
  assert.equal(invalidURL.isError, true);
});

test('Claude installer preserves preferences and other servers; changes require explicit replacement', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'figma-spark-claude-config-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const configPath = join(directory, 'claude_desktop_config.json');
  const previous = { preferences: { theme: 'dark' }, mcpServers: { other: { command: '/fixture/other' } } };
  await writeFile(configPath, JSON.stringify(previous));
  const installed = await installClaudeDesktop({ configPath });
  t.after(() => rm(installed.backup, { force: true }));
  const config = JSON.parse(await readFile(configPath, 'utf8'));
  assert.deepEqual(config.preferences, previous.preferences);
  assert.deepEqual(config.mcpServers.other, previous.mcpServers.other);
  assert.ok(config.mcpServers['figma-spark'].args[0].endsWith('/bridge/claude.mjs'));
  assert.ok(!JSON.stringify(config.mcpServers['figma-spark']).includes('token'));
  assert.deepEqual(JSON.parse(await readFile(installed.backup, 'utf8')), previous);
  assert.equal((await installClaudeDesktop({ configPath })).alreadyInstalled, true);
  config.mcpServers['figma-spark'].command = '/different/command';
  await writeFile(configPath, JSON.stringify(config));
  await assert.rejects(installClaudeDesktop({ configPath }), /--update/);
  const updated = await installClaudeDesktop({ configPath, update: true });
  t.after(() => rm(updated.backup, { force: true }));
  assert.equal(JSON.parse(await readFile(updated.backup, 'utf8')).mcpServers['figma-spark'].command, '/different/command');
});
